version: "3.9"
services:
  backend:
    build: backend
    ports:
      - "8081"
    environment:
      - SERVER_LOG_LEVEL=info
      - SERVER_HOOKS=${SERVER_HOOKS:-chatac.hooks.DefaultChatHooks}
      - SERVER_HOOKS_PARAMS=${SERVER_HOOKS_PARAMS}
  nginx:
    build: frontend
    ports:
      - "${NGINX_PORT:-8080}:8080"
    #volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/conf.d/chatac.conf:ro
    #  - ./frontend/build:/frontend:ro
