<?php

$animals=
array(
    "Aardvark",
    "Albatros",
    "Alligator",
    "Alpaga",
    "Fourmi",
    "Fourmilier",
    "Antilope",
    "Singe",
    "Tatou",
    "ane",
    "Babouin",
    "Blaireau",
    "Barracuda",
    "Chauve-souris",
    "Ours",
    "Castor",
    "Abeille",
    "Bison",
    "Sanglier",
    "Buffle",
    "Papillon",
    "Chameau",
    "Capybara",
    "Caribou",
    "Cassowary",
    "Chat",
    "Chenille",
    "Bovin",
    "Chamois",
    "Guépard",
    "Poulet",
    "Chimpanzé",
    "Chinchilla",
    "Chough",
    "Palourde",
    "Cobra",
    "Cafard",
    "Morue",
    "Cormoran",
    "Coyote",
    "Crabe",
    "Grue",
    "Crocodile",
    "Corbeau",
    "Courlis",
    "Cerf",
    "Dinosaure",
    "Chien",
    "Dogfish",
    "Dauphin",
    "Dotterel",
    "colombe",
    "Libellule",
    "Canard",
    "Dugong",
    "Bécasseau variable",
    "Aigle",
    "Echidné",
    "Anguille",
    "Eland",
    "Eléphant",
    "Elan",
    "emeu",
    "Faucon",
    "Furet",
    "Pinson",
    "Poisson",
    "Flamant",
    "Mouche",
    "Renard",
    "Grenouille",
    "Gaur",
    "Gazelle",
    "Gerbille",
    "Girafe",
    "Gnat",
    "Gnou",
    "Chèvre",
    "Chardonneret",
    "Poisson rouge",
    "Oie",
    "Gorille",
    "Autour des palombes",
    "Sauterelle",
    "Tétras",
    "Guanaco",
    "Goéland",
    "Hamster",
    "Lièvre",
    "Faucon",
    "Hérisson",
    "Héron",
    "Hareng",
    "Hippopotame",
    "Frelon",
    "Cheval",
    "Humain",
    "Colibri",
    "Hyène",
    "bouquetin",
    "Ibis",
    "chacal",
    "Jaguar",
    "Jay",
    "méduse",
    "Kangourou",
    "Martin-pêcheur",
    "Koala",
    "Kookabura",
    "Kouprey",
    "Koudou",
    "Vanneau",
    "Alouette",
    "Lémurien",
    "Léopard",
    "Lion",
    "lama",
    "Homard",
    "Criquet",
    "Loris",
    "Pou",
    "Oiseau lyre",
    "Pie",
    "Colvert",
    "Lamantin",
    "Mandrill",
    "Mante",
    "martre",
    "Suricate",
    "Vison",
    "Taupe",
    "Mangouste",
    "Singe",
    "elan",
    "Moustique",
    "Souris",
    "Mule",
    "Narval",
    "triton",
    "rossignol",
    "Pieuvre",
    "Okapi",
    "Opossum",
    "Oryx",
    "Autruche",
    "Loutre",
    "Hibou",
    "Huître",
    "Panthère",
    "Perroquet",
    "Perdrix",
    "Pafowl",
    "Pélican",
    "Pingouin",
    "Faisan",
    "Cochon",
    "Pigeon",
    "Poney",
    "Porc-épic",
    "Marsouin",
    "Caille",
    "Quelea",
    "Quetzal",
    "Lapin",
    "raton laveur",
    "Rail",
    "bélier",
    "Rat",
    "Corbeau",
    "cerf rouge",
    "panda rouge",
    "Renne",
    "Rhinocéros",
    "Tour",
    "Salamandre",
    "Saumon",
    "Dollar de sable",
    "Bécasseau",
    "Sardine",
    "Scorpion",
    "Hippocampe",
    "Phoque",
    "Requin",
    "Mouton",
    "Musaraigne",
    "mouffette",
    "Escargot",
    "Serpent",
    "moineau",
    "Araignée",
    "Spatule",
    "Calamar",
    "Ecureuil",
    "etourneau",
    "pastenague",
    "Punaise",
    "Cigogne",
    "hirondelle",
    "cygne",
    "Tapir",
    "Tarsier",
    "Termite",
    "Tigre",
    "Crapaud",
    "Truite",
    "Dinde",
    "Tortue",
    "Vipère",
    "Vautour",
    "Wallaby",
    "Morse",
    "Guêpe",
    "Belette",
    "Baleine",
    "Chat sauvage",
    "Loup",
    "Carcajou",
    "Wombat",
    "Bécasse",
    "Pic",
    "Ver",
    "Troglodyte",
    "Yak",
    "Zèbre"
);
function Unaccent($string)
{
    return preg_replace('~&([a-z]{1,2})(acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);~i', '$1', htmlentities($string, ENT_QUOTES, 'UTF-8'));
}

// map to uppercase
$animals = array_map('strtoupper', $animals);

// Liste des animaux triés par ordre alphabétique (qui nous servira pour ajouter des bonus de points aux joueurs)
$animalsListUppercase = $animals;


$groupedAnimals = array();
foreach ($animals as $animal) {
    $firstLetter = substr($animal, 0, 1);
    // remove accents and to uppercase
    $firstLetter = Unaccent($firstLetter);
    $firstLetter = strtoupper($firstLetter);

    
    if (!isset($groupedAnimals[$firstLetter])) {
        $groupedAnimals[$firstLetter] = array();
    }
    $groupedAnimals[$firstLetter][] = $animal;
}

ksort($groupedAnimals);


?>