<?php

$animalsFRA=
array(
    "Aardvark",
    "Albatros",
    "Alligator",
    "Alpaga",
    "Fourmi",
    "Fourmilier",
    "Antilope",
    "Singe",
    "Tatou",
    "ane",
    "Babouin",
    "Blaireau",
    "Barracuda",
    "Chauve-souris",
    "Ours",
    "Castor",
    "Abeille",
    "Bison",
    "Sanglier",
    "Buffle",
    "Papillon",
    "Chameau",
    "Capybara",
    "Caribou",
    "Cassowary",
    "Chat",
    "Chenille",
    "Bovin",
    "Chamois",
    "Guépard",
    "Poulet",
    "Chimpanzé",
    "Chinchilla",
    "Chough",
    "Palourde",
    "Cobra",
    "Cafard",
    "Morue",
    "Cormoran",
    "Coyote",
    "Crabe",
    "Grue",
    "Crocodile",
    "Corbeau",
    "Courlis",
    "Cerf",
    "Dinosaure",
    "Chien",
    "Dogfish",
    "Dauphin",
    "Dotterel",
    "colombe",
    "Libellule",
    "Canard",
    "Dugong",
    "Bécasseau variable",
    "Aigle",
    "Echidné",
    "Anguille",
    "Eland",
    "Eléphant",
    "Elan",
    "emeu",
    "Faucon",
    "Furet",
    "Pinson",
    "Poisson",
    "Flamant",
    "Mouche",
    "Renard",
    "Grenouille",
    "Gaur",
    "Gazelle",
    "Gerbille",
    "Girafe",
    "Gnat",
    "Gnou",
    "Chèvre",
    "Chardonneret",
    "Poisson rouge",
    "Oie",
    "Gorille",
    "Autour des palombes",
    "Sauterelle",
    "Tétras",
    "Guanaco",
    "Goéland",
    "Hamster",
    "Lièvre",
    "Faucon",
    "Hérisson",
    "Héron",
    "Hareng",
    "Hippopotame",
    "Frelon",
    "Cheval",
    "Humain",
    "Colibri",
    "Hyène",
    "bouquetin",
    "Ibis",
    "chacal",
    "Jaguar",
    "Jay",
    "méduse",
    "Kangourou",
    "Martin-pêcheur",
    "Koala",
    "Kookabura",
    "Kouprey",
    "Koudou",
    "Vanneau",
    "Alouette",
    "Lémurien",
    "Léopard",
    "Lion",
    "lama",
    "Homard",
    "Criquet",
    "Loris",
    "Pou",
    "Oiseau lyre",
    "Pie",
    "Colvert",
    "Lamantin",
    "Mandrill",
    "Mante",
    "martre",
    "Suricate",
    "Vison",
    "Taupe",
    "Mangouste",
    "Singe",
    "elan",
    "Moustique",
    "Souris",
    "Mule",
    "Narval",
    "triton",
    "rossignol",
    "Pieuvre",
    "Okapi",
    "Opossum",
    "Oryx",
    "Autruche",
    "Loutre",
    "Hibou",
    "Huître",
    "Panthère",
    "Perroquet",
    "Perdrix",
    "Pafowl",
    "Pélican",
    "Pingouin",
    "Faisan",
    "Cochon",
    "Pigeon",
    "Poney",
    "Porc-épic",
    "Marsouin",
    "Caille",
    "Quelea",
    "Quetzal",
    "Lapin",
    "raton laveur",
    "Rail",
    "bélier",
    "Rat",
    "Corbeau",
    "cerf rouge",
    "panda rouge",
    "Renne",
    "Rhinocéros",
    "Tour",
    "Salamandre",
    "Saumon",
    "Dollar de sable",
    "Bécasseau",
    "Sardine",
    "Scorpion",
    "Hippocampe",
    "Phoque",
    "Requin",
    "Mouton",
    "Musaraigne",
    "mouffette",
    "Escargot",
    "Serpent",
    "moineau",
    "Araignée",
    "Spatule",
    "Calamar",
    "Ecureuil",
    "etourneau",
    "pastenague",
    "Punaise",
    "Cigogne",
    "hirondelle",
    "cygne",
    "Tapir",
    "Tarsier",
    "Termite",
    "Tigre",
    "Crapaud",
    "Truite",
    "Dinde",
    "Tortue",
    "Vipère",
    "Vautour",
    "Wallaby",
    "Morse",
    "Guêpe",
    "Belette",
    "Baleine",
    "Chat sauvage",
    "Loup",
    "Carcajou",
    "Wombat",
    "Bécasse",
    "Pic",
    "Ver",
    "Troglodyte",
    "Yak",
    "Zèbre"
);

$animalsENG = array(
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Armadillo",
    "Donkey",
    "Baboon",
    "Badger",
    "Barracuda",
    "Bat",
    "Bear",
    "Beaver",
    "Bee",
    "Bison",
    "Boar",
    "Buffalo",
    "Butterfly",
    "Camel",
    "Capybara",
    "Caribou",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Cattle",
    "Chamois",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chough",
    "Clam",
    "Cobra",
    "Cockroach",
    "Cod",
    "Cormorant",
    "Coyote",
    "Crab",
    "Crane",
    "Crocodile",
    "Crow",
    "Curlew",
    "Deer",
    "Dinosaur",
    "Dog",
    "Dogfish",
    "Dolphin",
    "Dotterel",
    "Dove",
    "Dragonfly",
    "Duck",
    "Dugong",
    "Dunlin",
    "Eagle",
    "Echidna",
    "Eel",
    "Eland",
    "Elephant",
    "Elk",
    "Emu",
    "Falcon",
    "Ferret",
    "Finch",
    "Fish",
    "Flamingo",
    "Fly",
    "Fox",
    "Frog",
    "Gaur",
    "Gazelle",
    "Gerbil",
    "Giraffe",
    "Gnat",
    "Gnu",
    "Goat",
    "Goldfinch",
    "Goldfish",
    "Goose",
    "Gorilla",
    "Goshawk",
    "Grasshopper",
    "Grouse",
    "Guanaco",
    "Gull",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Human",
    "Hummingbird",
    "Hyena",
    "Ibex",
    "Ibis",
    "Jackal",
    "Jaguar",
    "Jay",
    "Jellyfish",
    "Kangaroo",
    "Kingfisher",
    "Koala",
    "Kookabura",
    "Kouprey",
    "Kudu",
    "Lapwing",
    "Lark",
    "Lemur",
    "Leopard",
    "Lion",
    "Llama",
    "Lobster",
    "Locust",
    "Loris",
    "Louse",
    "Lyrebird",
    "Magpie",
    "Mallard",
    "Manatee",
    "Mandrill",
    "Mantis",
    "Marten",
    "Meerkat",
    "Mink",
    "Mole",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Mouse",
    "Mule",
    "Narwhal",
    "Newt",
    "Nightingale",
    "Octopus",
    "Okapi",
    "Opossum",
    "Oryx",
    "Ostrich",
    "Otter",
    "Owl",
    "Oyster",
    "Panther",
    "Parrot",
    "Partridge",
    "Peafowl",
    "Pelican",
    "Penguin",
    "Pheasant",
    "Pig",
    "Pigeon",
    "Pony",
    "Porcupine",
    "Porpoise",
    "Quail",
    "Quelea",
    "Quetzal",
    "Rabbit",
    "Raccoon",
    "Rail",
    "Ram",
    "Rat",
    "Raven",
    "Red deer",
    "Red panda",
    "Reindeer",
    "Rhinoceros",
    "Rook",
    "Salamander",
    "Salmon",
    "Sand Dollar",
    "Sandpiper",
    "Sardine",
    "Scorpion",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Shrew",
    "Skunk",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Spoonbill",
    "Squid",
    "Squirrel",
    "Starling",
    "Stingray",
    "Stinkbug",
    "Stork",
    "Swallow",
    "Swan",
    "Tapir",
    "Tarsier",
    "Termite",
    "Tiger",
    "Toad",
    "Trout",
    "Turkey",
    "Turtle",
    "Viper",
    "Vulture",
    "Wallaby",
    "Walrus",
    "Wasp",
    "Weasel",
    "Whale",
    "Wildcat",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodcock",
    "Woodpecker",
    "Worm",
    "Wren",
    "Yak",
    "Zebra"
);

function isWordInFRAList($word, $list){
    $word = strtolower($word);
    $list = array_map('strtolower', $list);
    return in_array($word, $list);
}	


function getDatasOfAnimalENG($animalENG){
    $curl = curl_init();

        curl_setopt_array($curl, [
            CURLOPT_URL => "https://animals-by-api-ninjas.p.rapidapi.com/v1/animals?name=cheetah",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "GET",
            CURLOPT_HTTPHEADER => [
                "X-RapidAPI-Host: animals-by-api-ninjas.p.rapidapi.com",
                "X-RapidAPI-Key: SIGN-UP-FOR-KEY"
            ],
        ]);

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
            echo "cURL Error #:" . $err;
        } else {
           json_decode($response, true);
            return $response;
        }
}

function getDatasOfAnimalFRA($animalFRA){
    global $animalsFRA;
    if (in_array($animalFRA, $animalsFRA)) {
        $animalENG = array_search($animalFRA, $animalsFRA);
        return getDatasOfAnimalENG($animalENG);
    }

}

function Unaccent($string)
{
    return preg_replace('~&([a-z]{1,2})(acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);~i', '$1', htmlentities($string, ENT_QUOTES, 'UTF-8'));
}

// // map to uppercase
// foreach ($animals as $key => $animal) {
//     $animals[$key] = Unaccent($animal);
//     $animals[$key] = strtoupper($animals[$key]);
// }

// // Liste des animaux triés par ordre alphabétique (qui nous servira pour ajouter des bonus de points aux joueurs)
// $animalsListUppercase = $animals;


/* 
$groupedAnimals = array();
foreach ($animals as $animal) {
    $firstLetter = substr($animal, 0, 1);
    // remove accents and to uppercase
    $firstLetter = Unaccent($firstLetter);
    $firstLetter = strtoupper($firstLetter);

    
    if (!isset($groupedAnimals[$firstLetter])) {
        $groupedAnimals[$firstLetter] = array();
    }
    $groupedAnimals[$firstLetter][] = $animal;
}

ksort($groupedAnimals); */



?>